version: '3.7'
services:
  mock-server:
    image: up9inc/wiremock-studio:2.32.0-18
    ports: 
      - "8000-8100:8000-8100"
      - "9000:9000"
    volumes:
      - ./wiremock:/home/wiremock

# https://wiremock.org/studio/docs/getting-started/docker/
