swagger: "2.0"
info:
  version: 1.0.0
  title: Music Library API
paths:
  /songs:
    get:
      summary: Returns a list of all songs in the library
      description: Retrieve a list of songs in the library
      produces:
        - application/json
      parameters:
        - name: limit
          in: query
          description: The maximum number of songs to return
          type: integer
          format: int32
          default: 100
          minimum: 1
          maximum: 1000
        - name: offset
          in: query
          description: The number of songs to skip before starting to return results
          type: integer
          format: int32
          default: 0
          minimum: 0
      responses:
        200:
          description: A list of songs
          schema:
            type: array
            items:
              $ref: '#/definitions/Song'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
        500:
          description: Internal server error
    post:
      summary: Add a new song to the library
      description: Add a new song to the library
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: song
          in: body
          description: The song to add
          schema:
            $ref: '#/definitions/SongInput'
      responses:
        201:
          description: The added song
          schema:
            $ref: '#/definitions/Song'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        500:
          description: Internal server error
definitions:
  Song:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      artist:
        type: string
      album:
        type: string
      year:
        type: integer
        format: int32
      duration:
        type: integer
        format: int32
  SongInput:
    type: object
    required:
      - title
      - artist
    properties:
      title:
        type: string
      artist:
        type: string
      album:
        type: string
      year:
        type: integer
        format: int32
      duration:
        type: integer
        format: int32
