swagger: '2.0'
info:
  version: 1.0.0
  title: API de Usuario
  description: API para administrar usuarios y sus datos asociados
basePath: /api/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

# Definición del esquema de Usuario
definitions:
  Usuario:
    type: object
    required:
      - id
      - nombre
    properties:
      id:
        type: integer
        format: int64
      nombre:
        type: string

# Definición de los endpoints para Consulta de Usuario
paths:
  /usuarios/{id}:
    get:
      summary: Consultar los datos de un usuario
      description: Retorna los detalles de un usuario específico
      parameters:
        - in: path
          name: id
          description: El ID del usuario a obtener
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Usuario'
          examples:
            application/json:
              {
                "id": 123,
                "nombre": "Juan Pérez"
              }
        '404':
          description: No encontrado

  /usuarios/{id}/imagenes:
    get:
      summary: Consultar imágenes de un usuario
      description: Retorna las imágenes asociadas a un usuario específico
      parameters:
        - in: path
          name: id
          description: El ID del usuario cuyas imágenes se quieren obtener
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: string
          examples:
            application/json:
              [
                "https://example.com/imagen1.jpg",
                "https://example.com/imagen2.jpg",
                "https://example.com/imagen3.jpg"
              ]
        '404':
          description: No encontrado

  /usuarios/{id}/saldo:
    get:
      summary: Consultar el saldo de un usuario
      description: Retorna el saldo disponible de un usuario específico
      parameters:
        - in: path
          name: id
          description: El ID del usuario cuyo saldo se quiere obtener
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              saldo:
                type: number
                format: double
          examples:
            application/json:
              {
                "saldo": 1200.50
              }
        '404':
          description: No encontrado

  /usuarios/{id}/factura:
    get:
      summary: Consultar la factura de un usuario
      description: Retorna la factura de un usuario específico
      parameters:
        - in: path
          name: id
          description: El ID del usuario cuya factura se quiere obtener
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            type: object
            properties:
              fecha:
                type: string
                format: date
              monto:
                type: number
                format: double
              items:
                type: array
                items:
                  type: object
                  properties:
                    nombre:
                      type: string
                    cantidad:
                      type: number
