version: '3.7'
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "9080:8080"

# https://hub.docker.com/r/swaggerapi/swagger-editor/tags
# https://github.com/swagger-api/swagger-editor