swagger: "2.0"
info:
  version: 1.0.0
  title: Music Library API
paths:
  /songs:
    get:
      summary: Get all songs
      responses:
        200:
          description: Successful operation
        401:
          description: Unauthorized
        403:
          description: Forbidden
    post:
      summary: Add a new song
      parameters:
        - name: song
          in: body
          schema:
            $ref: '#/definitions/Song'
          required: true
      responses:
        201:
          description: Song created successfully
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /songs/{id}:
    get:
      summary: Get a song by ID
      parameters:
        - name: id
          in: path
          type: integer
          required: true
      responses:
        200:
          description: Successful operation
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Song not found
    put:
      summary: Update a song by ID
      parameters:
        - name: id
          in: path
          type: integer
          required: true
        - name: song
          in: body
          schema:
            $ref: '#/definitions/Song'
          required: true
      responses:
        200:
          description: Song updated successfully
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Song not found
    delete:
      summary: Delete a song by ID
      parameters:
        - name: id
          in: path
          type: integer
          required: true
      responses:
        204:
          description: Song deleted successfully
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Song not found
  /login:
    post:
      summary: Authenticate user
      parameters:
        - name: credentials
          in: body
          schema:
            $ref: '#/definitions/Credentials'
          required: true
      responses:
        200:
          description: Login successful
        401:
          description: Unauthorized

definitions:
  Song:
    type: object
    properties:
      song_name:
        type: string
      artist_name:
        type: string

  Credentials:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
