swagger: '2.0'
info:
  version: 1.0.0
  title: Tienda de Comida API
  description: API para administrar productos en una tienda de comida
basePath: /api/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

# Definición del esquema de Producto
definitions:
  Producto:
    type: object
    required:
      - id
      - nombre
      - descripcion
      - precio
    properties:
      id:
        type: integer
        format: int64
      nombre:
        type: string
      descripcion:
        type: string
      precio:
        type: number
        format: double

# Definición de los endpoints para CRUD de Productos
paths:
  /producto:
    get:
      summary: Obtener todos los productos
      description: Retorna una lista de todos los productos en la tienda
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Producto'
    post:
      summary: Crear un nuevo producto
      description: Crea un nuevo producto en la tienda
      parameters:
        - in: body
          name: producto
          description: Los detalles del producto a crear
          required: true
          schema:
            $ref: '#/definitions/Producto'
      responses:
        '201':
          description: Creado
          schema:
            $ref: '#/definitions/Producto'

  /producto/{id}:
    get:
      summary: Obtener un producto por ID
      description: Retorna los detalles de un producto específico
      parameters:
        - in: path
          name: id
          description: El ID del producto a obtener
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Producto'
        '404':
          description: No encontrado
    put:
      summary: Actualizar un producto existente
      description: Actualiza los detalles de un producto existente en la tienda
      parameters:
        - in: path
          name: id
          description: El ID del producto a actualizar
          required: true
          type: integer
          format: int64
        - in: body
          name: producto
          description: Los detalles actualizados del producto
          required: true
          schema:
            $ref: '#/definitions/Producto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Producto'
        '404':
          description: No encontrado
    delete:
      summary: Eliminar un producto existente
      description: Elimina un producto existente de la tienda
      parameters:
        - in: path
          name: id
          description: El ID del producto a eliminar
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: Sin contenido
        '404':
          description: No encontrado
